update: Dockerfile (#454)
* Dockerfile の内容を整理
  * sudo 追加
  * openssh-client 追加
  * vscode user で sudo できるように追加
  * fish shell への変更を vscode の設定に変更

Co-authored-by: Naoki Aoyama <naaoyama@bbtower.co.jp>

diff --git a/.devcontainer/Dockerfile b/.devcontainer/Dockerfile
--- a/.devcontainer/Dockerfile
+++ b/.devcontainer/Dockerfile
@@ -1,45 +1,58 @@
 FROM python:3.10.14-slim-bullseye
-ENV DEBIAN_FRONTEND=noninteractive \
-    PYTHONFAULTHANDLER=1 \
-    PYTHONUNBUFFERED=1 \
-    PYTHONHASHSEED=random \
-    PIP_NO_CACHE_DIR=off \
+
+ARG PIP_DEFAULT_TIMEOUT=100 \
     PIP_DISABLE_PIP_VERSION_CHECK=on \
-    PIP_DEFAULT_TIMEOUT=100 \
+    PIP_NO_CACHE_DIR=off \
+    PYTHONFAULTHANDLER=1 \
+    PYTHONHASHSEED=random \
+    PYTHONUNBUFFERED=1 \
+    DEBIAN_FRONTEND=noninteractive \
+    \
     POETRY_VERSION=1.8.2
 
-RUN \
-    set -eux \
-    && apt-get update \
-    && apt-get upgrade -y \
-    && apt-get install -y \
+ENV TZ=Asia/Tokyo
+
+SHELL [ "/bin/bash", "-c" ]
+
+# set Timezone
+RUN set -eux && \
+    ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
+
+RUN set -eux && \
+    apt -y update && \
+    apt -y upgrade && \
+    apt -y install --no-install-recommends \
+    bash \
     ca-certificates \
     curl \
-    gnupg \
-    lsb-release \
-    \
-    && apt-get update \
-    && apt-get -y install \
     fish \
-    curl \
     git \
+    gpg-agent \
+    nano \
+    openssh-client \
+    software-properties-common \
+    sudo \
+    wget && \
     \
-    && apt-get clean \
-    && rm -rf /var/lib/apt/lists/*
+    # Cleanup \
+    apt -y autoremove && \
+    apt -y clean && \
+    rm -rf /var/lib/apt/lists/*
 
-RUN pip install "poetry==$POETRY_VERSION"
+# Create user
+RUN set -eux && \
+    groupadd --gid 1000 vscode && \
+    useradd -s /bin/bash --uid 1000 --gid 1000 -m vscode && \
+    echo vscode:password | chpasswd && \
+    passwd -d vscode && \
+    echo -e "vscode\tALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/vscode
 
-ARG USERNAME=vscode
-ARG USER_UID=1000
-ARG USER_GID=1000
-RUN \
-    set -eux \
-    && groupadd --gid $USER_GID $USERNAME \
-    && useradd -s /usr/bin/fish --uid $USER_UID --gid $USER_GID -m $USERNAME
+RUN set -eux && \
+    pip install "poetry==${POETRY_VERSION}" && \
+    type poetry
 
-USER $USERNAME
-
-RUN \
-    set -eux \
-    && /usr/bin/fish -c 'curl -sL https://git.io/fisher | source && fisher install jorgebucaran/fisher' \
-    && /usr/bin/fish -c 'fisher install oh-my-fish/theme-bobthefish'
+# User lavel settings
+USER vscode
+RUN set -eux && \
+    /usr/bin/fish -c 'curl -sL https://git.io/fisher | source && fisher install jorgebucaran/fisher' && \
+    /usr/bin/fish -c 'fisher install oh-my-fish/theme-bobthefish'
